server:
  port: ${PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true


egorcery:
  security:
    jwt:
      tokenExpirationTime: 43800 # Number of minutes => 1 month
      refreshTokenExpTime: 131400 # 3 months
      tokenIssuer: http://egrocery.ma
      tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus